---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: project
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: project
  minReplicas: 3
  maxReplicas: 40
  targetCPUUtilizationPercentage: 25